/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.4.1/userguide/java_library_plugin.html
 */

buildscript{
    ext.kotlin_version = '1.3.31'
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
plugins {
    // Apply the java-library plugin to add support for Java Library
//    `java-library`
    apply plugin: 'kotlin'
    apply plugin: 'application'
    mainClassName = 'com.programming.kotlin.chapter01.ProgramKt'

}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    mavenCentral()
}

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
//    api("org.apache.commons:commons-math3:3.6.1")
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    testCommpile 'io.kotlintest:kotlintest-runner-junit5:3.3.2'

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
//    implementation("com.google.guava:guava:27.0.1-jre")

    // Use JUnit test framework
//    testImplementation("junit:junit:4.12")
}
